import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={geistSans.className}>
        <nav className="bg-white shadow mb-6">
          <div className="max-w-6xl mx-auto px-4 py-3 flex gap-4 items-center">
            <a href="/" className="font-bold text-lg text-blue-700">الرئيسية</a>
            <a href="/products" className="text-gray-700 hover:text-blue-700">المنتجات</a>
            <a href="/login" className="text-gray-700 hover:text-blue-700 ml-auto">تسجيل الدخول</a>
            <a href="/register" className="text-gray-700 hover:text-blue-700">تسجيل جديد</a>
            <a href="/profile" className="text-gray-700 hover:text-blue-700">الملف الشخصي</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
